cat << 'EOF' > docker-compose.ym
services:
  api:
    build: .
    container_name: food_ai_backend
    restart: unless-stopped
    ports:
      - "8081:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
EOF